version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: flask_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
